version: '3.7'
services:
  back-end:
    container_name: NestAPI
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - docker.env
    volumes:
      - ./src:/src
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - back-tier

  postgres:
    container_name: DB-NestAPI
    image: postgres
    restart: always
    networks:
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db-NestAPI-data:/var/lib/postgresql/data
    env_file:
      - docker.env

networks:
  back-tier:

volumes:
  db-NestAPI-data: